import{bg as l,bh as t}from"./main-CwplE3lg.js";const y=l({id:"record-store",state:()=>({errors:[],successMessage:""}),actions:{async fetchRecord(r=1,e="",s=null,a=null,n=null,c="",i=null,u=null,d=null,p=null){try{return await t("/course-detail",{method:"GET",headers:{"Content-Type":"application/json"},params:{page:r,searchQuery:e,countryId:s,intakeId:a,universityId:n,courseName:c,courseType:i,editorID:u,dateFrom:d,dateTo:p}})}catch(o){throw console.error("Error getting application list:",o),this.errors=o.response?o.response.data.errors:["An unexpected error occurred"],o}},async submitApplication(r){try{const e=await t("/course-detail",{method:"POST",body:r,headers:{"Content-Type":"application/json"}});return this.successMessage="Data submitted successfully",e.data}catch(e){throw console.error("Error submitting application:",e),this.errors=e.response?e.response.data.errors:["An unexpected error occurred"],e}},async submitEditApplication(r,e){try{const s=await t(`/course-detail/${r}`,{method:"PUT",body:e,headers:{"Content-Type":"application/json"}});return this.successMessage="Data submitted successfully",s.data}catch(s){throw console.error("Error submitting application:",s),this.errors=s.response?s.response.data.errors:["An unexpected error occurred"],s}},async deleteRecord(r){try{await t(`/course-detail/${r}`,{method:"DELETE"})}catch(e){console.error("Error deleting course details:",e),this.errors=e.response?e.response.data.errors:["An unexpected error occurred"]}},async requestForm(r){try{const e=await t("/request-record",{method:"POST",body:r,headers:{"Content-Type":"application/json"}});return this.successMessage="Request submitted successfully",e.data}catch(e){throw console.error("Error submitting request form:",e),this.errors=e.response?e.response.data.errors:["An unexpected error occurred"],e}}}});export{y as u};
